server:
  port: 8081
  servlet:
    session:
      timeout: 7d


spring:
  web:
    locale: en
    locale-resolver: fixed
  thymeleaf:
    cache: false
    enabled: true
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/

personalblog:
  account:
    - username: admin
      password: "{noop}admin"
      roles: "ADMIN"
    - username: kirito
      password: "{noop}123456"
      roles: "USER"
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
